-- 📊 데이터 분석가(SQL) 팩 문항 42행. 재실행 안전(해당 팩만 지우고 다시 넣는다).
-- 개수는 20/10/12 — 클라이언트 PACK_N 과 같아야 한다. 어긋나면 그 팩만 번들로 되돌아간다.
DELETE FROM content WHERE pack = 'data:sql';
INSERT INTO content (pack, kind, slot, a, b, c, d) VALUES
  ('data:sql', 'bug', 0, 'SELCT id FROM users;', 'SELECT id FROM users;', 'ERROR: syntax error at or near "SELCT"', 'SELCT'),
  ('data:sql', 'bug', 1, 'SELECT * FORM orders;', 'SELECT * FROM orders;', 'ERROR: syntax error at or near "FORM"', 'FORM'),
  ('data:sql', 'bug', 2, 'DELETE FROM cart WEHRE id = 7;', 'DELETE FROM cart WHERE id = 7;', 'ERROR: syntax error at or near "WEHRE"', 'WEHRE'),
  ('data:sql', 'bug', 3, 'SELECT * FROM cart ORDRE BY id;', 'SELECT * FROM cart ORDER BY id;', 'ERROR: syntax error at or near "ORDRE"', 'ORDRE'),
  ('data:sql', 'bug', 4, 'GORUP BY uid, region', 'GROUP BY uid, region', 'ERROR: syntax error at or near "GORUP"', 'GORUP'),
  ('data:sql', 'bug', 5, 'INNER JION pay USING (oid)', 'INNER JOIN pay USING (oid)', 'ERROR: syntax error at or near "JION"', 'JION'),
  ('data:sql', 'bug', 6, 'INSETR INTO sales (d, amt)', 'INSERT INTO sales (d, amt)', 'ERROR: syntax error at or near "INSETR"', 'INSETR'),
  ('data:sql', 'bug', 7, 'CREATE TABEL mart (id INT);', 'CREATE TABLE mart (id INT);', 'ERROR: syntax error at or near "TABEL"', 'TABEL'),
  ('data:sql', 'bug', 8, 'SELECT SUM(amt FROM sales;', 'SELECT SUM(amt) FROM sales;', 'ERROR: syntax error at or near "FROM"', ') 닫는 괄호'),
  ('data:sql', 'bug', 9, 'SELECT "userId" FROM users;', 'SELECT user_id FROM users;', 'ERROR: column "userId" does not exist', '큰따옴표 대소문자'),
  ('data:sql', 'bug', 10, 'SELECT u.emial FROM users u;', 'SELECT u.email FROM users u;', 'ERROR: column u.emial does not exist', 'emial'),
  ('data:sql', 'bug', 11, 'WHERE deleted_at = NULL', 'WHERE deleted_at IS NULL', 'NULL 은 = 로 비교할 수 없습니다 — 항상 0행이 나옵니다', '= NULL → IS NULL'),
  ('data:sql', 'bug', 12, 'SELECT DISTICT uid FROM cart;', 'SELECT DISTINCT uid FROM cart;', 'ERROR: syntax error at or near "DISTICT"', 'DISTICT'),
  ('data:sql', 'bug', 13, 'HAVNG COUNT(*) > 3', 'HAVING COUNT(*) > 3', 'ERROR: syntax error at or near "HAVNG"', 'HAVNG'),
  ('data:sql', 'bug', 14, 'SELECT d, COUNT(*) FROM log;', 'SELECT d, COUNT(*) FROM log GROUP BY d;', 'ERROR: column "log.d" must appear in the GROUP BY clause', 'GROUP BY 누락'),
  ('data:sql', 'bug', 15, 'OVER (PARITION BY uid)', 'OVER (PARTITION BY uid)', 'ERROR: syntax error at or near "PARITION"', 'PARITION'),
  ('data:sql', 'bug', 16, 'COALSECE(amt, 0) AS amt', 'COALESCE(amt, 0) AS amt', 'ERROR: function coalsece(numeric, integer) does not exist', 'COALSECE'),
  ('data:sql', 'bug', 17, 'WHERE d > now() - 7', 'WHERE d > now() - INTERVAL ''7 days''', 'ERROR: operator does not exist: timestamp - integer', 'INTERVAL ''7 days'''),
  ('data:sql', 'bug', 18, 'paid / total AS rate', 'paid::numeric / total AS rate', '정수끼리 나눠서 소수점이 버려집니다 — 0 만 나옵니다', '::numeric 캐스팅'),
  ('data:sql', 'bug', 19, 'SELECT COUNT(status) FROM orders;', 'SELECT COUNT(*) FROM orders;', 'COUNT(컬럼) 은 NULL 을 안 셉니다 — 전체 행 수와 다릅니다', 'COUNT(*) 로'),
  ('data:sql', 'commit', 0, 'psql -f daily_sales.sql', NULL, NULL, NULL),
  ('data:sql', 'commit', 1, 'dbt run --select daily_sales', NULL, NULL, NULL),
  ('data:sql', 'commit', 2, 'dbt test --select orders', NULL, NULL, NULL),
  ('data:sql', 'commit', 3, 'airflow dags trigger daily_kpi', NULL, NULL, NULL),
  ('data:sql', 'commit', 4, 'git commit -m "fix: group by uid"', NULL, NULL, NULL),
  ('data:sql', 'commit', 5, 'git commit -m "feat: cohort table"', NULL, NULL, NULL),
  ('data:sql', 'commit', 6, 'bq query --use_legacy_sql=false', NULL, NULL, NULL),
  ('data:sql', 'commit', 7, 'python etl/backfill.py --days 7', NULL, NULL, NULL),
  ('data:sql', 'commit', 8, 'git push origin main', NULL, NULL, NULL),
  ('data:sql', 'commit', 9, 'make refresh-marts', NULL, NULL, NULL),
  ('data:sql', 'slack', 0, '이 지표 왜 떨어졌나요?', '원인 보고 있습니다', NULL, NULL),
  ('data:sql', 'slack', 1, '대시보드 갱신됐나요?', '방금 새로고침했습니다', NULL, NULL),
  ('data:sql', 'slack', 2, '이 숫자 맞는 건가요?', '원본이랑 대조했습니다', NULL, NULL),
  ('data:sql', 'slack', 3, '쿼리 좀 봐주실 수 있나요?', '이따 확인해드릴게요', NULL, NULL),
  ('data:sql', 'slack', 4, '어제 적재 실패했나요?', '재실행 걸어뒀습니다', NULL, NULL),
  ('data:sql', 'slack', 5, '코호트 뽑아주실 수 있나요?', '내일까지 드리겠습니다', NULL, NULL),
  ('data:sql', 'slack', 6, '이 지표 정의 어디 있죠?', '위키에 정리해뒀습니다', NULL, NULL),
  ('data:sql', 'slack', 7, '집계가 두 배로 나와요', '조인 조건 보겠습니다', NULL, NULL),
  ('data:sql', 'slack', 8, '테이블 권한 좀 주세요', '방금 부여했습니다', NULL, NULL),
  ('data:sql', 'slack', 9, '이번 주 매출 얼마죠?', '지표방에 올려뒀습니다', NULL, NULL),
  ('data:sql', 'slack', 10, '쿼리가 너무 느린데요', '인덱스 확인하겠습니다', NULL, NULL),
  ('data:sql', 'slack', 11, '샘플링 없이 볼 수 있나요?', '전체로 다시 돌립니다', NULL, NULL);
