-- 팩 콘텐츠(버그·커밋·슬랙)를 DB 로.
--
-- 왜 — 문항을 고치는 데 배포가 필요 없어진다. SQL 한 줄이면 즉시 반영되고
-- GitHub Pages 캐시 10분도 안 기다린다. 팩을 늘리는 비용이 콘텐츠 작성 시간만 남는다.
--
-- PRIMARY KEY (pack, kind, slot) 이 **슬롯 중복을 스키마에서 막는다.**
-- bug 는 0~11, commit 은 0~5, slack 은 0~7 이 정확히 차야 한다.
-- 개수가 안 맞으면 클라이언트가 **번들된 기본 배열로 되돌린다** — 서버가 죽어도 게임은 돈다.
--
-- 컬럼이 a/b/c/d 로 무명인 이유: kind 마다 의미가 다르다.
--   bug     a=bad(미리 채워질 문장)  b=fix(정답)  c=err(증상)  d=tok(6초 힌트)
--   commit  a=문장
--   slack   a=질문  b=답장(이것만 타이핑한다)
--
-- 재실행 안전: DELETE 후 INSERT 라 몇 번을 돌려도 같은 상태가 된다.
CREATE TABLE IF NOT EXISTS content (
  pack TEXT NOT NULL,
  kind TEXT NOT NULL,
  slot INTEGER NOT NULL,
  a TEXT NOT NULL,
  b TEXT,
  c TEXT,
  d TEXT,
  PRIMARY KEY (pack, kind, slot)
);

DELETE FROM content;
INSERT INTO content (pack, kind, slot, a, b, c, d) VALUES
  ('dev:js', 'bug', 0, 'fpr (let i = 0; i < 10; i++) {', 'for (let i = 0; i < 10; i++) {', 'SyntaxError: unexpected token ''fpr''', 'fpr'),
  ('dev:js', 'bug', 1, 'lf (user.isAdmin) {', 'if (user.isAdmin) {', 'SyntaxError: unexpected token ''lf''', 'lf'),
  ('dev:js', 'bug', 2, 'retrun total;', 'return total;', 'SyntaxError: unexpected token ''retrun''', 'retrun'),
  ('dev:js', 'bug', 3, 'consol.log(items.length);', 'console.log(items.length);', 'ReferenceError: consol is not defined', 'consol'),
  ('dev:js', 'bug', 4, 'whlie (queue.length) {', 'while (queue.length) {', 'SyntaxError: unexpected token ''whlie''', 'whlie'),
  ('dev:js', 'bug', 5, 'improt React from ''react'';', 'import React from ''react'';', 'SyntaxError: unexpected token ''improt''', 'improt'),
  ('dev:js', 'bug', 6, 'cosnt name = ''admin'';', 'const name = ''admin'';', 'SyntaxError: unexpected identifier ''cosnt''', 'cosnt'),
  ('dev:js', 'bug', 7, 'elsif (score > 90) {', 'else if (score > 90) {', 'SyntaxError: unexpected token ''elsif''', 'elsif'),
  ('dev:js', 'bug', 8, 'const arr = [1, 2, 3;', 'const arr = [1, 2, 3];', 'SyntaxError: missing ] after element list', '] 닫는 괄호'),
  ('dev:js', 'bug', 9, 'document.getElementByid(''app'')', 'document.getElementById(''app'')', 'TypeError: getElementByid is not a function', 'ById 대소문자'),
  ('dev:js', 'bug', 10, 'return arr.lenght;', 'return arr.length;', 'undefined 반환 — 프로퍼티 이름을 확인하세요', 'lenght'),
  ('dev:js', 'bug', 11, 'if (count = 0) {', 'if (count === 0) {', '조건문에 대입(=)이 쓰였습니다 — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:js', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:js', 'commit', 1, 'git commit -m "hotfix: null check"', NULL, NULL, NULL),
  ('dev:js', 'commit', 2, 'git commit -m "chore: remove log"', NULL, NULL, NULL),
  ('dev:js', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:js', 'commit', 4, 'git push origin main', NULL, NULL, NULL),
  ('dev:js', 'commit', 5, 'npm test -- --run', NULL, NULL, NULL),
  ('dev:js', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:js', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:js', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:js', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:js', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:js', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:js', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:js', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:kotlin', 'bug', 0, 'fpr (i in 0 until 10) {', 'for (i in 0 until 10) {', 'Syntax error: unexpected token ''fpr''', 'fpr'),
  ('dev:kotlin', 'bug', 1, 'lf (user.isAdmin) {', 'if (user.isAdmin) {', 'Syntax error: unexpected token ''lf''', 'lf'),
  ('dev:kotlin', 'bug', 2, 'retrun total', 'return total', 'Syntax error: unexpected token ''retrun''', 'retrun'),
  ('dev:kotlin', 'bug', 3, 'pritnln(items.size)', 'println(items.size)', 'Unresolved reference: pritnln', 'pritnln'),
  ('dev:kotlin', 'bug', 4, 'whlie (queue.isNotEmpty()) {', 'while (queue.isNotEmpty()) {', 'Syntax error: unexpected token ''whlie''', 'whlie'),
  ('dev:kotlin', 'bug', 5, 'improt kotlinx.coroutines.*', 'import kotlinx.coroutines.*', 'Syntax error: unexpected token ''improt''', 'improt'),
  ('dev:kotlin', 'bug', 6, 'vla name = "admin"', 'val name = "admin"', 'Syntax error: unexpected token ''vla''', 'vla'),
  ('dev:kotlin', 'bug', 7, 'esle if (score > 90) {', 'else if (score > 90) {', 'Syntax error: unexpected token ''esle''', 'esle'),
  ('dev:kotlin', 'bug', 8, 'val arr = listOf(1, 2, 3', 'val arr = listOf(1, 2, 3)', 'Syntax error: expecting '')''', ') 닫는 괄호'),
  ('dev:kotlin', 'bug', 9, 'if (name.IsEmpty()) {', 'if (name.isEmpty()) {', 'Unresolved reference: IsEmpty', 'IsEmpty 대소문자'),
  ('dev:kotlin', 'bug', 10, 'return arr.siez', 'return arr.size', 'Unresolved reference: siez — 프로퍼티 이름을 확인하세요', 'siez'),
  ('dev:kotlin', 'bug', 11, 'if (count = 0) {', 'if (count == 0) {', 'Assignments are not expressions — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:kotlin', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 1, 'git commit -m "hotfix: NPE guard"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 2, 'git commit -m "chore: bump ktlint"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 4, 'git push origin main', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 5, './gradlew test', NULL, NULL, NULL),
  ('dev:kotlin', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:kotlin', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:kotlin', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:kotlin', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:swift', 'bug', 0, 'fro i in 0..<10 {', 'for i in 0..<10 {', 'Syntax error: unexpected token ''fro''', 'fro'),
  ('dev:swift', 'bug', 1, 'fi user.isAdmin {', 'if user.isAdmin {', 'Syntax error: unexpected token ''fi''', 'fi'),
  ('dev:swift', 'bug', 2, 'retrun total', 'return total', 'Syntax error: unexpected token ''retrun''', 'retrun'),
  ('dev:swift', 'bug', 3, 'pirnt(items.count)', 'print(items.count)', 'Cannot find ''pirnt'' in scope', 'pirnt'),
  ('dev:swift', 'bug', 4, 'whlie !queue.isEmpty {', 'while !queue.isEmpty {', 'Syntax error: unexpected token ''whlie''', 'whlie'),
  ('dev:swift', 'bug', 5, 'improt Foundation', 'import Foundation', 'Syntax error: unexpected token ''improt''', 'improt'),
  ('dev:swift', 'bug', 6, 'lte name = "admin"', 'let name = "admin"', 'Syntax error: unexpected token ''lte''', 'lte'),
  ('dev:swift', 'bug', 7, 'esle if score > 90 {', 'else if score > 90 {', 'Syntax error: unexpected token ''esle''', 'esle'),
  ('dev:swift', 'bug', 8, 'let arr = [1, 2, 3', 'let arr = [1, 2, 3]', 'Syntax error: expected '']'' in array literal', '] 닫는 괄호'),
  ('dev:swift', 'bug', 9, 'if name.IsEmpty {', 'if name.isEmpty {', 'Value of type ''String'' has no member ''IsEmpty''', 'IsEmpty 대소문자'),
  ('dev:swift', 'bug', 10, 'return arr.cont', 'return arr.count', 'Value of type ''[Int]'' has no member ''cont''', 'cont'),
  ('dev:swift', 'bug', 11, 'if count = 0 {', 'if count == 0 {', 'Use of ''='' in a boolean context — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:swift', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 1, 'git commit -m "hotfix: unwrap crash"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 2, 'git commit -m "chore: bump swiftlint"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 4, 'git push origin main', NULL, NULL, NULL),
  ('dev:swift', 'commit', 5, 'swift test', NULL, NULL, NULL),
  ('dev:swift', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:swift', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:swift', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:swift', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:swift', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:swift', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('pm:policy', 'bug', 0, '쿠폰은 1만원 이하 주문 시 3천원 할인', '쿠폰은 1만원 이상 주문 시 3천원 할인', 'CS 제보 — 3만원 주문인데 할인이 안 됩니다. 최소금액 조건이 뒤집혔습니다', '이하 → 이상'),
  ('pm:policy', 'bug', 1, '프로모션 기간: 8/30 오픈 ~ 8/24 종료', '프로모션 기간: 8/30 오픈 ~ 9/24 종료', '기간이 음수로 계산됩니다 — 종료일이 시작일보다 앞섭니다', '8/24 → 9/24'),
  ('pm:policy', 'bug', 2, '무료배송 기준: 30,000월 이상 결제', '무료배송 기준: 30,000원 이상 결제', '단위 표기 오류 — ''월''이 아니라 ''원''입니다', '월 → 원'),
  ('pm:policy', 'bug', 3, '무료배송 기준 금액은 3,000원이다', '무료배송 기준 금액은 30,000원이다', '전 주문이 무료배송으로 나갑니다 — 자릿수를 확인하세요', '3,000 → 30,000'),
  ('pm:policy', 'bug', 4, '수수료를 2%에서 3%로 1% 인상한다', '수수료를 2%에서 3%로 1%p 인상한다', '정산팀 문의 — 인상폭 표기가 애매합니다. %와 %p를 구분해주세요', '1% → 1%p'),
  ('pm:policy', 'bug', 5, '회원 등급: 실버, 골드, 다이야', '회원 등급: 실버, 골드, 다이아', '등급명 오타 — 화면에 ''다이야''로 노출됩니다', '다이야 → 다이아'),
  ('pm:policy', 'bug', 6, '비회원도 쿠폰을 사용할 수 있다', '비회원도 쿠폰을 사용할 수 없다', '기획서와 반대로 동작합니다 — 비회원은 쿠폰 사용 불가입니다', '있다 → 없다'),
  ('pm:policy', 'bug', 7, '주문 취소는 발송 후에만 가능하다', '주문 취소는 발송 전에만 가능하다', '발송된 주문이 취소되고 있습니다 — 발송 전에만 가능해야 합니다', '후 → 전'),
  ('pm:policy', 'bug', 8, '전환율 = 주문 120 / 방문 3,000 = 0.4%', '전환율 = 주문 120 / 방문 3,000 = 4%', '대시보드 수치가 실제와 10배 차이납니다 — 계산이 틀렸습니다', '0.4% → 4%'),
  ('pm:policy', 'bug', 9, '1인 1매 한정, 최대 3매까지 구매', '1인 3매 한정, 최대 3매까지 구매', '개발팀 문의 — 앞뒤 수량 조건이 서로 다릅니다', '1매 한정 → 3매 한정'),
  ('pm:policy', 'bug', 10, '결제 취소는 3.2절을 참고한다', '결제 취소는 4.1절을 참고한다', '3.2절은 배송 정책입니다 — 결제 취소는 4.1절입니다', '3.2절 → 4.1절'),
  ('pm:policy', 'bug', 11, '배송 마감 시각: 오후 2시 (12:00)', '배송 마감 시각: 오후 2시 (14:00)', '표기된 두 시각이 다릅니다 — 24시간 표기를 맞춰주세요', '12:00 → 14:00'),
  ('pm:policy', 'commit', 0, '[확정] 쿠폰 정책 v2.1', NULL, NULL, NULL),
  ('pm:policy', 'commit', 1, '[긴급] 프로모션 롤백 요청', NULL, NULL, NULL),
  ('pm:policy', 'commit', 2, '[정리] 스펙 코멘트 반영 완료', NULL, NULL, NULL),
  ('pm:policy', 'commit', 3, '[확정] 비회원 결제 오픈', NULL, NULL, NULL),
  ('pm:policy', 'commit', 4, '릴리즈 노트 공유드립니다', NULL, NULL, NULL),
  ('pm:policy', 'commit', 5, 'QA 시나리오 검토 완료', NULL, NULL, NULL),
  ('pm:policy', 'slack', 0, '이 정책 확정된 건가요?', '오늘 안에 확정합니다', NULL, NULL),
  ('pm:policy', 'slack', 1, 'CS 문의 답변 주셨나요?', '확인하고 회신했습니다', NULL, NULL),
  ('pm:policy', 'slack', 2, '요구사항 반영됐나요?', '문서에 업데이트했습니다', NULL, NULL),
  ('pm:policy', 'slack', 3, '일정 하루 당길 수 있나요?', '검토해보겠습니다', NULL, NULL),
  ('pm:policy', 'slack', 4, '이거 왜 이렇게 정했죠?', '배경 정리해서 드릴게요', NULL, NULL),
  ('pm:policy', 'slack', 5, '개발팀에 전달됐나요?', '티켓 만들어뒀습니다', NULL, NULL),
  ('pm:policy', 'slack', 6, '지표 어떻게 나왔나요?', '대시보드 공유드릴게요', NULL, NULL),
  ('pm:policy', 'slack', 7, '유관부서 합의됐나요?', '내일 미팅 잡혀 있습니다', NULL, NULL),
  ('design:design', 'bug', 0, 'contrast: 3.2:1', 'contrast: 4.5:1', 'QA — 저시력 사용자가 본문을 못 읽습니다. 본문 대비 하한은 4.5:1 입니다', '3.2 → 4.5'),
  ('design:design', 'bug', 1, 'tap-area: 36px', 'tap-area: 44px', 'QA — 아이폰 SE 에서 버튼이 안 눌립니다. 터치 영역 하한은 44px 입니다', '36 → 44'),
  ('design:design', 'bug', 2, 'background: #ffffff', 'background: color-bg-base', 'QA — 다크모드에서 배경이 흰색으로 남습니다. 하드코딩 대신 토큰을 쓰세요', '#ffffff → color-bg-base'),
  ('design:design', 'bug', 3, 'spacing-5: 18px', 'spacing-5: 20px', 'QA — 카드 간격이 그리드에서 어긋납니다. 스페이싱 스케일은 4의 배수입니다', '18 → 20'),
  ('design:design', 'bug', 4, 'text-body-md: 13px', 'text-body-md: 16px', 'QA — 본문이 캡션보다 작아 보입니다. 본문 기본은 16px 입니다', '13 → 16'),
  ('design:design', 'bug', 5, 'icon: ic_cart_20', 'icon: ic_cart_24', 'QA — 장바구니 아이콘만 작습니다. 이 화면은 24 세트입니다', '20 → 24'),
  ('design:design', 'bug', 6, 'focus-ring: none', 'focus-ring: 2px', 'QA — 키보드로 이동할 때 지금 어디인지 안 보입니다. 포커스 링은 2px 입니다', 'none → 2px'),
  ('design:design', 'bug', 7, 'disabled: opacity 0.9', 'disabled: opacity 0.4', 'QA — 비활성 버튼이 눌리는 줄 압니다. 비활성 투명도는 0.4 입니다', '0.9 → 0.4'),
  ('design:design', 'bug', 8, 'transition: 600ms', 'transition: 200ms', 'QA — 화면 전환이 답답합니다. 표준 전환은 200ms 입니다', '600 → 200'),
  ('design:design', 'bug', 9, 'shadow: rgba(0, 0, 0, .12', 'shadow: rgba(0, 0, 0, .12)', 'QA — 그림자가 아예 안 들어갑니다', ') 닫는 괄호'),
  ('design:design', 'bug', 10, 'radius-lg: 10px', 'radius-lg: 12px', 'QA — 카드 모서리가 버튼과 안 맞습니다. lg 는 12px 입니다', '10 → 12'),
  ('design:design', 'bug', 11, 'Modal z-index: 10', 'Modal z-index: 1000', 'QA — 모달이 헤더 뒤로 숨습니다. 모달 레이어는 1000 입니다', '10 → 1000'),
  ('design:design', 'commit', 0, 'Button/Primary/Hover', NULL, NULL, NULL),
  ('design:design', 'commit', 1, 'Card/Product/Sold-out', NULL, NULL, NULL),
  ('design:design', 'commit', 2, 'Modal/Confirm/Default', NULL, NULL, NULL),
  ('design:design', 'commit', 3, 'Input/Search/Focused', NULL, NULL, NULL),
  ('design:design', 'commit', 4, 'Chip/Filter/Selected', NULL, NULL, NULL),
  ('design:design', 'commit', 5, 'ic_cart_24.svg', NULL, NULL, NULL),
  ('design:design', 'slack', 0, '시안 언제 볼 수 있나요?', '오늘 중으로 공유합니다', NULL, NULL),
  ('design:design', 'slack', 1, '이거 컴포넌트 있나요?', '라이브러리에 있습니다', NULL, NULL),
  ('design:design', 'slack', 2, '다크모드도 되나요?', '토큰으로 대응했습니다', NULL, NULL),
  ('design:design', 'slack', 3, '개발 전달 끝났나요?', 'Dev Mode 열어뒀습니다', NULL, NULL),
  ('design:design', 'slack', 4, '아이콘 하나만 더 될까요?', '내보내서 드릴게요', NULL, NULL),
  ('design:design', 'slack', 5, '이 여백 왜 이런가요?', '스페이싱 스케일입니다', NULL, NULL),
  ('design:design', 'slack', 6, '피그마 권한 좀 주세요', '방금 초대했습니다', NULL, NULL),
  ('design:design', 'slack', 7, '시안 두 개 중 뭐가 낫죠?', '첫 번째를 추천드립니다', NULL, NULL);
