-- ☕ Java 팩 문항 42행. 재실행 안전(해당 팩만 지우고 다시 넣는다).
-- 개수는 20/10/12 — 클라이언트 PACK_N 과 같아야 한다. 어긋나면 그 팩만 번들로 되돌아간다.
DELETE FROM content WHERE pack = 'dev:java';
INSERT INTO content (pack, kind, slot, a, b, c, d) VALUES
  ('dev:java', 'bug', 0, 'fpr (int i = 0; i < 10; i++) {', 'for (int i = 0; i < 10; i++) {', 'error: illegal start of expression', 'fpr'),
  ('dev:java', 'bug', 1, 'lf (user.isAdmin()) {', 'if (user.isAdmin()) {', 'error: cannot find symbol — lf', 'lf'),
  ('dev:java', 'bug', 2, 'retrun total;', 'return total;', 'error: cannot find symbol: retrun', 'retrun'),
  ('dev:java', 'bug', 3, 'System.out.printn(size);', 'System.out.println(size);', 'cannot find symbol: method printn(int)', 'printn'),
  ('dev:java', 'bug', 4, 'whlie (!queue.isEmpty()) {', 'while (!queue.isEmpty()) {', 'error: illegal start of expression', 'whlie'),
  ('dev:java', 'bug', 5, 'improt java.util.List;', 'import java.util.List;', 'error: class, interface, or enum expected', 'improt'),
  ('dev:java', 'bug', 6, 'pubic class Order {', 'public class Order {', 'error: illegal start of type', 'pubic'),
  ('dev:java', 'bug', 7, 'esle if (score > 90) {', 'else if (score > 90) {', 'error: ''else'' without ''if''', 'esle'),
  ('dev:java', 'bug', 8, 'int[] arr = {1, 2, 3;', 'int[] arr = {1, 2, 3};', 'error: ''}'' expected', '} 닫는 중괄호'),
  ('dev:java', 'bug', 9, 'if (name.equalsIgnorecase("a")) {', 'if (name.equalsIgnoreCase("a")) {', 'cannot find symbol: method equalsIgnorecase(String)', 'Case 대소문자'),
  ('dev:java', 'bug', 10, 'return arr.lenght;', 'return arr.length;', 'cannot find symbol: variable lenght', 'lenght'),
  ('dev:java', 'bug', 11, 'if (a == b) return true;', 'if (a.equals(b)) return true;', '문자열을 == 로 비교했습니다 — 값이 같아도 false 가 나옵니다', '== → equals'),
  ('dev:java', 'bug', 12, 'vra list = new ArrayList<>();', 'var list = new ArrayList<>();', 'cannot find symbol: class vra', 'vra'),
  ('dev:java', 'bug', 13, 'recrod User(String name) {}', 'record User(String name) {}', 'error: class, interface, enum, or record expected', 'recrod'),
  ('dev:java', 'bug', 14, 'items.collect(Collecters.toList())', 'items.collect(Collectors.toList())', 'cannot find symbol: variable Collecters', 'Collecters'),
  ('dev:java', 'bug', 15, 'Optional.ofNullalbe(user)', 'Optional.ofNullable(user)', 'cannot find symbol: method ofNullalbe(User)', 'ofNullalbe'),
  ('dev:java', 'bug', 16, 'swich (state) { case "a" -> 1; }', 'switch (state) { case "a" -> 1; }', 'error: illegal start of expression', 'swich'),
  ('dev:java', 'bug', 17, 'public statc void main(String[] a)', 'public static void main(String[] a)', 'error: illegal start of type', 'statc'),
  ('dev:java', 'bug', 18, 'Stirng name = "admin";', 'String name = "admin";', 'cannot find symbol: class Stirng', 'Stirng'),
  ('dev:java', 'bug', 19, 'int count = "5";', 'int count = 5;', 'incompatible types: String cannot be converted to int', '"5" → 5'),
  ('dev:java', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:java', 'commit', 1, 'git commit -m "hotfix: NPE guard"', NULL, NULL, NULL),
  ('dev:java', 'commit', 2, 'git commit -m "chore: bump spotless"', NULL, NULL, NULL),
  ('dev:java', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:java', 'commit', 4, 'git commit -m "refactor: use stream"', NULL, NULL, NULL),
  ('dev:java', 'commit', 5, 'git commit -m "test: add junit case"', NULL, NULL, NULL),
  ('dev:java', 'commit', 6, 'git commit -m "perf: cache lookup"', NULL, NULL, NULL),
  ('dev:java', 'commit', 7, 'git commit --amend --no-edit', NULL, NULL, NULL),
  ('dev:java', 'commit', 8, 'git push origin main', NULL, NULL, NULL),
  ('dev:java', 'commit', 9, 'mvn -q test', NULL, NULL, NULL),
  ('dev:java', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:java', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:java', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:java', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:java', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:java', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:java', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:java', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:java', 'slack', 8, 'CI 가 계속 빨간데요', '플레이키 테스트입니다', NULL, NULL),
  ('dev:java', 'slack', 9, '이거 스펙 맞나요?', '티켓 다시 보겠습니다', NULL, NULL),
  ('dev:java', 'slack', 10, '장애 원인 나왔나요?', '곧 공유드리겠습니다', NULL, NULL),
  ('dev:java', 'slack', 11, 'QA 반영 언제 되죠?', '다음 배포에 들어갑니다', NULL, NULL);
