-- 팩 문항 전면 개정 — bugs 12→20 · commits 6→10 · slacks 8→12.
-- 요즘 실제로 나는 실수(await fetch, 화살표 중괄호, setTimeout(fn()), coroutine, SwiftUI)와
-- 법무·정산·QA 고증을 넣었다. 재실행 안전(DELETE 후 INSERT).
--
-- ⚠️ 개수를 바꾸면 클라이언트 validPack() 이 그 팩을 통째로 번들 배열로 되돌린다.
--    "SQL 넣었는데 왜 그대로지?" 의 원인이 된다. 20/10/12 를 지킬 것.
DELETE FROM content;
INSERT INTO content (pack, kind, slot, a, b, c, d) VALUES
  ('dev:js', 'bug', 0, 'fpr (let i = 0; i < 10; i++) {', 'for (let i = 0; i < 10; i++) {', 'SyntaxError: unexpected token ''fpr''', 'fpr'),
  ('dev:js', 'bug', 1, 'lf (user.isAdmin) {', 'if (user.isAdmin) {', 'SyntaxError: unexpected token ''lf''', 'lf'),
  ('dev:js', 'bug', 2, 'retrun total;', 'return total;', 'SyntaxError: unexpected token ''retrun''', 'retrun'),
  ('dev:js', 'bug', 3, 'consol.log(items.length);', 'console.log(items.length);', 'ReferenceError: consol is not defined', 'consol'),
  ('dev:js', 'bug', 4, 'whlie (queue.length) {', 'while (queue.length) {', 'SyntaxError: unexpected token ''whlie''', 'whlie'),
  ('dev:js', 'bug', 5, 'improt React from ''react'';', 'import React from ''react'';', 'SyntaxError: unexpected token ''improt''', 'improt'),
  ('dev:js', 'bug', 6, 'cosnt name = ''admin'';', 'const name = ''admin'';', 'SyntaxError: unexpected identifier ''cosnt''', 'cosnt'),
  ('dev:js', 'bug', 7, 'elsif (score > 90) {', 'else if (score > 90) {', 'SyntaxError: unexpected token ''elsif''', 'elsif'),
  ('dev:js', 'bug', 8, 'const arr = [1, 2, 3;', 'const arr = [1, 2, 3];', 'SyntaxError: missing ] after element list', '] 닫는 괄호'),
  ('dev:js', 'bug', 9, 'document.getElementByid(''app'')', 'document.getElementById(''app'')', 'TypeError: getElementByid is not a function', 'ById 대소문자'),
  ('dev:js', 'bug', 10, 'return arr.lenght;', 'return arr.length;', 'undefined 반환 — 프로퍼티 이름을 확인하세요', 'lenght'),
  ('dev:js', 'bug', 11, 'if (count = 0) {', 'if (count === 0) {', '조건문에 대입(=)이 쓰였습니다 — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:js', 'bug', 12, 'const d = await fetch(u).json();', 'const d = await (await fetch(u)).json();', 'TypeError: fetch(...).json is not a function', 'await 를 한 번 더'),
  ('dev:js', 'bug', 13, 'const r = arr.map(x => { x * 2 });', 'const r = arr.map(x => x * 2);', '[undefined, undefined] 가 나옵니다 — 화살표 함수가 반환을 안 합니다', '{ } 중괄호'),
  ('dev:js', 'bug', 14, 'setTimeout(retry(), 1000);', 'setTimeout(retry, 1000);', '1초 뒤가 아니라 즉시 실행됩니다', 'retry() 의 괄호'),
  ('dev:js', 'bug', 15, 'if (typeof x === ''undefiend'') {', 'if (typeof x === ''undefined'') {', '이 조건이 항상 false 입니다', 'undefiend'),
  ('dev:js', 'bug', 16, 'const copy = {..obj, id};', 'const copy = {...obj, id};', 'SyntaxError: Unexpected token ''.''', '점 개수'),
  ('dev:js', 'bug', 17, 'export defualt App;', 'export default App;', 'SyntaxError: unexpected token ''defualt''', 'defualt'),
  ('dev:js', 'bug', 18, 'useEfect(() => {}, []);', 'useEffect(() => {}, []);', 'ReferenceError: useEfect is not defined', 'useEfect'),
  ('dev:js', 'bug', 19, 'const [a, b] = {x: 1, y: 2};', 'const {x, y} = {x: 1, y: 2};', 'TypeError: object is not iterable — 구조분해 형태가 틀렸습니다', '[ ] 와 { }'),
  ('dev:js', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:js', 'commit', 1, 'git commit -m "hotfix: null check"', NULL, NULL, NULL),
  ('dev:js', 'commit', 2, 'git commit -m "chore: remove log"', NULL, NULL, NULL),
  ('dev:js', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:js', 'commit', 4, 'git commit -m "refactor: extract hook"', NULL, NULL, NULL),
  ('dev:js', 'commit', 5, 'git commit -m "test: add edge case"', NULL, NULL, NULL),
  ('dev:js', 'commit', 6, 'git commit -m "perf: memoize list"', NULL, NULL, NULL),
  ('dev:js', 'commit', 7, 'git commit --amend --no-edit', NULL, NULL, NULL),
  ('dev:js', 'commit', 8, 'git push origin main', NULL, NULL, NULL),
  ('dev:js', 'commit', 9, 'npm test -- --run', NULL, NULL, NULL),
  ('dev:js', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:js', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:js', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:js', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:js', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:js', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:js', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:js', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:js', 'slack', 8, 'CI 가 계속 빨간데요', '플레이키 테스트입니다', NULL, NULL),
  ('dev:js', 'slack', 9, '이거 스펙 맞나요?', '티켓 다시 보겠습니다', NULL, NULL),
  ('dev:js', 'slack', 10, '장애 원인 나왔나요?', '곧 공유드리겠습니다', NULL, NULL),
  ('dev:js', 'slack', 11, 'QA 반영 언제 되죠?', '다음 배포에 들어갑니다', NULL, NULL),
  ('dev:kotlin', 'bug', 0, 'fpr (i in 0 until 10) {', 'for (i in 0 until 10) {', 'Syntax error: unexpected token ''fpr''', 'fpr'),
  ('dev:kotlin', 'bug', 1, 'lf (user.isAdmin) {', 'if (user.isAdmin) {', 'Syntax error: unexpected token ''lf''', 'lf'),
  ('dev:kotlin', 'bug', 2, 'retrun total', 'return total', 'Syntax error: unexpected token ''retrun''', 'retrun'),
  ('dev:kotlin', 'bug', 3, 'pritnln(items.size)', 'println(items.size)', 'Unresolved reference: pritnln', 'pritnln'),
  ('dev:kotlin', 'bug', 4, 'whlie (queue.isNotEmpty()) {', 'while (queue.isNotEmpty()) {', 'Syntax error: unexpected token ''whlie''', 'whlie'),
  ('dev:kotlin', 'bug', 5, 'improt kotlinx.coroutines.*', 'import kotlinx.coroutines.*', 'Syntax error: unexpected token ''improt''', 'improt'),
  ('dev:kotlin', 'bug', 6, 'vla name = "admin"', 'val name = "admin"', 'Syntax error: unexpected token ''vla''', 'vla'),
  ('dev:kotlin', 'bug', 7, 'esle if (score > 90) {', 'else if (score > 90) {', 'Syntax error: unexpected token ''esle''', 'esle'),
  ('dev:kotlin', 'bug', 8, 'val arr = listOf(1, 2, 3', 'val arr = listOf(1, 2, 3)', 'Syntax error: expecting '')''', ') 닫는 괄호'),
  ('dev:kotlin', 'bug', 9, 'if (name.IsEmpty()) {', 'if (name.isEmpty()) {', 'Unresolved reference: IsEmpty', 'IsEmpty 대소문자'),
  ('dev:kotlin', 'bug', 10, 'return arr.siez', 'return arr.size', 'Unresolved reference: siez — 프로퍼티 이름을 확인하세요', 'siez'),
  ('dev:kotlin', 'bug', 11, 'if (count = 0) {', 'if (count == 0) {', 'Assignments are not expressions — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:kotlin', 'bug', 12, 'viewModelScope.launc {', 'viewModelScope.launch {', 'Unresolved reference: launc', 'launc'),
  ('dev:kotlin', 'bug', 13, 'supsend fun load() {', 'suspend fun load() {', 'Syntax error: unexpected token ''supsend''', 'supsend'),
  ('dev:kotlin', 'bug', 14, 'data calss User(val id: Int)', 'data class User(val id: Int)', 'Syntax error: unexpected token ''calss''', 'calss'),
  ('dev:kotlin', 'bug', 15, 'user?.lat { show(it) }', 'user?.let { show(it) }', 'Unresolved reference: lat', 'lat'),
  ('dev:kotlin', 'bug', 16, 'whn (state) { else -> 0 }', 'when (state) { else -> 0 }', 'Syntax error: unexpected token ''whn''', 'whn'),
  ('dev:kotlin', 'bug', 17, 'if (value is Strng) {', 'if (value is String) {', 'Unresolved reference: Strng', 'Strng'),
  ('dev:kotlin', 'bug', 18, 'val n: Int? = null; n!!.inc()', 'val n: Int? = null; n?.inc()', 'NullPointerException — !! 대신 안전 호출을 쓰세요', '!! 두 개'),
  ('dev:kotlin', 'bug', 19, 'return list.frist()', 'return list.first()', 'Unresolved reference: frist', 'frist'),
  ('dev:kotlin', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 1, 'git commit -m "hotfix: NPE guard"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 2, 'git commit -m "chore: bump ktlint"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 4, 'git commit -m "refactor: use flow"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 5, 'git commit -m "test: add unit test"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 6, 'git commit -m "perf: lazy init"', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 7, 'git commit --amend --no-edit', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 8, 'git push origin main', NULL, NULL, NULL),
  ('dev:kotlin', 'commit', 9, './gradlew test', NULL, NULL, NULL),
  ('dev:kotlin', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:kotlin', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:kotlin', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:kotlin', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:kotlin', 'slack', 8, 'CI 가 계속 빨간데요', '플레이키 테스트입니다', NULL, NULL),
  ('dev:kotlin', 'slack', 9, '이거 스펙 맞나요?', '티켓 다시 보겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 10, '장애 원인 나왔나요?', '곧 공유드리겠습니다', NULL, NULL),
  ('dev:kotlin', 'slack', 11, 'QA 반영 언제 되죠?', '다음 배포에 들어갑니다', NULL, NULL),
  ('dev:swift', 'bug', 0, 'fro i in 0..<10 {', 'for i in 0..<10 {', 'Syntax error: unexpected token ''fro''', 'fro'),
  ('dev:swift', 'bug', 1, 'fi user.isAdmin {', 'if user.isAdmin {', 'Syntax error: unexpected token ''fi''', 'fi'),
  ('dev:swift', 'bug', 2, 'retrun total', 'return total', 'Syntax error: unexpected token ''retrun''', 'retrun'),
  ('dev:swift', 'bug', 3, 'pirnt(items.count)', 'print(items.count)', 'Cannot find ''pirnt'' in scope', 'pirnt'),
  ('dev:swift', 'bug', 4, 'whlie !queue.isEmpty {', 'while !queue.isEmpty {', 'Syntax error: unexpected token ''whlie''', 'whlie'),
  ('dev:swift', 'bug', 5, 'improt Foundation', 'import Foundation', 'Syntax error: unexpected token ''improt''', 'improt'),
  ('dev:swift', 'bug', 6, 'lte name = "admin"', 'let name = "admin"', 'Syntax error: unexpected token ''lte''', 'lte'),
  ('dev:swift', 'bug', 7, 'esle if score > 90 {', 'else if score > 90 {', 'Syntax error: unexpected token ''esle''', 'esle'),
  ('dev:swift', 'bug', 8, 'let arr = [1, 2, 3', 'let arr = [1, 2, 3]', 'Syntax error: expected '']'' in array literal', '] 닫는 괄호'),
  ('dev:swift', 'bug', 9, 'if name.IsEmpty {', 'if name.isEmpty {', 'Value of type ''String'' has no member ''IsEmpty''', 'IsEmpty 대소문자'),
  ('dev:swift', 'bug', 10, 'return arr.cont', 'return arr.count', 'Value of type ''[Int]'' has no member ''cont''', 'cont'),
  ('dev:swift', 'bug', 11, 'if count = 0 {', 'if count == 0 {', 'Use of ''='' in a boolean context — 비교 연산자를 쓰세요', '= 하나뿐인 등호'),
  ('dev:swift', 'bug', 12, 'guard let u = user esle {', 'guard let u = user else {', 'Syntax error: expected ''else'' after guard condition', 'esle'),
  ('dev:swift', 'bug', 13, 'Tsak { await load() }', 'Task { await load() }', 'Cannot find ''Tsak'' in scope', 'Tsak'),
  ('dev:swift', 'bug', 14, '@Stat private var count = 0', '@State private var count = 0', 'Unknown attribute ''Stat''', 'Stat'),
  ('dev:swift', 'bug', 15, 'let d = try awaut load()', 'let d = try await load()', 'Cannot find ''awaut'' in scope', 'awaut'),
  ('dev:swift', 'bug', 16, 'func load() asyc throws {', 'func load() async throws {', 'Syntax error: unexpected token ''asyc''', 'asyc'),
  ('dev:swift', 'bug', 17, 'struct HomeView: Veiw {', 'struct HomeView: View {', 'Cannot find type ''Veiw'' in scope', 'Veiw'),
  ('dev:swift', 'bug', 18, '@Publised var items = []', '@Published var items = []', 'Unknown attribute ''Publised''', 'Publised'),
  ('dev:swift', 'bug', 19, 'return array.frist', 'return array.first', 'Value of type ''[Int]'' has no member ''frist''', 'frist'),
  ('dev:swift', 'commit', 0, 'git commit -m "fix typo"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 1, 'git commit -m "hotfix: unwrap crash"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 2, 'git commit -m "chore: bump swiftlint"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 3, 'git commit -m "fix: elevator bug"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 4, 'git commit -m "refactor: use async let"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 5, 'git commit -m "test: add snapshot"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 6, 'git commit -m "perf: cache image"', NULL, NULL, NULL),
  ('dev:swift', 'commit', 7, 'git commit --amend --no-edit', NULL, NULL, NULL),
  ('dev:swift', 'commit', 8, 'git push origin main', NULL, NULL, NULL),
  ('dev:swift', 'commit', 9, 'swift test', NULL, NULL, NULL),
  ('dev:swift', 'slack', 0, '배포 언제 나가나요?', '테스트 끝나면 나갑니다', NULL, NULL),
  ('dev:swift', 'slack', 1, '그 버그 재현되나요?', '로그 보고 있습니다', NULL, NULL),
  ('dev:swift', 'slack', 2, '코드리뷰 봐주실 수 있나요?', '이따 확인하겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 3, '서버 이상하다는데요?', '지표는 정상입니다', NULL, NULL),
  ('dev:swift', 'slack', 4, '롤백 해야 할까요?', '조금만 더 보겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 5, '그 PR 머지했나요?', '방금 올렸습니다', NULL, NULL),
  ('dev:swift', 'slack', 6, '핫픽스 가능한가요?', '지금 준비 중입니다', NULL, NULL),
  ('dev:swift', 'slack', 7, '로컬에선 되나요?', '저는 재현이 안 됩니다', NULL, NULL),
  ('dev:swift', 'slack', 8, 'CI 가 계속 빨간데요', '플레이키 테스트입니다', NULL, NULL),
  ('dev:swift', 'slack', 9, '이거 스펙 맞나요?', '티켓 다시 보겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 10, '장애 원인 나왔나요?', '곧 공유드리겠습니다', NULL, NULL),
  ('dev:swift', 'slack', 11, 'QA 반영 언제 되죠?', '다음 배포에 들어갑니다', NULL, NULL),
  ('pm:policy', 'bug', 0, '쿠폰은 1만원 이하 주문 시 3천원 할인', '쿠폰은 1만원 이상 주문 시 3천원 할인', 'CS 제보 — 3만원 주문인데 할인이 안 됩니다. 최소금액 조건이 뒤집혔습니다', '이하 → 이상'),
  ('pm:policy', 'bug', 1, '프로모션 기간: 8/30 오픈 ~ 8/24 종료', '프로모션 기간: 8/30 오픈 ~ 9/24 종료', '기간이 음수로 계산됩니다 — 종료일이 시작일보다 앞섭니다', '8/24 → 9/24'),
  ('pm:policy', 'bug', 2, '무료배송 기준: 30,000월 이상 결제', '무료배송 기준: 30,000원 이상 결제', '단위 표기 오류 — ''월''이 아니라 ''원''입니다', '월 → 원'),
  ('pm:policy', 'bug', 3, '무료배송 기준 금액은 3,000원이다', '무료배송 기준 금액은 30,000원이다', '전 주문이 무료배송으로 나갑니다 — 자릿수를 확인하세요', '3,000 → 30,000'),
  ('pm:policy', 'bug', 4, '수수료를 2%에서 3%로 1% 인상한다', '수수료를 2%에서 3%로 1%p 인상한다', '정산팀 문의 — 인상폭 표기가 애매합니다. %와 %p를 구분해주세요', '1% → 1%p'),
  ('pm:policy', 'bug', 5, '회원 등급: 실버, 골드, 다이야', '회원 등급: 실버, 골드, 다이아', '등급명 오타 — 화면에 ''다이야''로 노출됩니다', '다이야 → 다이아'),
  ('pm:policy', 'bug', 6, '비회원도 쿠폰을 사용할 수 있다', '비회원도 쿠폰을 사용할 수 없다', '기획서와 반대로 동작합니다 — 비회원은 쿠폰 사용 불가입니다', '있다 → 없다'),
  ('pm:policy', 'bug', 7, '주문 취소는 발송 후에만 가능하다', '주문 취소는 발송 전에만 가능하다', '발송된 주문이 취소되고 있습니다 — 발송 전에만 가능해야 합니다', '후 → 전'),
  ('pm:policy', 'bug', 8, '전환율 = 주문 120 / 방문 3,000 = 0.4%', '전환율 = 주문 120 / 방문 3,000 = 4%', '대시보드 수치가 실제와 10배 차이납니다 — 계산이 틀렸습니다', '0.4% → 4%'),
  ('pm:policy', 'bug', 9, '1인 1매 한정, 최대 3매까지 구매', '1인 3매 한정, 최대 3매까지 구매', '개발팀 문의 — 앞뒤 수량 조건이 서로 다릅니다', '1매 한정 → 3매 한정'),
  ('pm:policy', 'bug', 10, '결제 취소는 3.2절을 참고한다', '결제 취소는 4.1절을 참고한다', '3.2절은 배송 정책입니다 — 결제 취소는 4.1절입니다', '3.2절 → 4.1절'),
  ('pm:policy', 'bug', 11, '배송 마감 시각: 오후 2시 (12:00)', '배송 마감 시각: 오후 2시 (14:00)', '표기된 두 시각이 다릅니다 — 24시간 표기를 맞춰주세요', '12:00 → 14:00'),
  ('pm:policy', 'bug', 12, '단순 변심 반품은 수령 후 7일 이내', '단순 변심 반품은 수령 후 14일 이내', '법무 검토 — 전자상거래법상 청약철회 기간은 14일입니다', '7일 → 14일'),
  ('pm:policy', 'bug', 13, '적립금 유효기간은 발급일로부터 1년', '적립금 유효기간은 발급일로부터 2년', 'CS 제보 — 안내 메일에는 2년으로 나갔습니다. 표기가 서로 다릅니다', '1년 → 2년'),
  ('pm:policy', 'bug', 14, '쿠폰은 다른 쿠폰과 중복 사용 가능', '쿠폰은 다른 쿠폰과 중복 사용 불가', '정산팀 — 할인이 이중으로 적용돼 마진이 음수입니다', '가능 → 불가'),
  ('pm:policy', 'bug', 15, '등급 갱신은 매월 1일에 이루어진다', '등급 갱신은 매월 말일에 이루어진다', '개발팀 문의 — 배치는 말일에 도는데 문서는 1일로 되어 있습니다', '1일 → 말일'),
  ('pm:policy', 'bug', 16, '정산 주기는 주 1회 수요일이다', '정산 주기는 월 2회 수요일이다', '정산팀 — 실제 지급은 월 2회입니다. 문서만 주 1회로 남아 있습니다', '주 1회 → 월 2회'),
  ('pm:policy', 'bug', 17, '개인정보 보관 기간은 탈퇴 후 5년', '개인정보 보관 기간은 탈퇴 후 3년', '법무 검토 — 전자상거래 기록 보존 기준은 3년입니다', '5년 → 3년'),
  ('pm:policy', 'bug', 18, '최소 주문금액 50,000원 이상 결제', '최소 주문금액 5,000원 이상 결제', 'CS 문의 폭주 — 대부분의 장바구니가 주문 불가입니다. 자릿수를 확인하세요', '50,000 → 5,000'),
  ('pm:policy', 'bug', 19, '리뷰 작성 시 적립금 500원 지급', '리뷰 작성 시 적립금 50원 지급', '정산팀 — 리뷰 예산이 3일 만에 소진됐습니다. 단가를 확인하세요', '500 → 50'),
  ('pm:policy', 'commit', 0, '[확정] 쿠폰 정책 v2.1', NULL, NULL, NULL),
  ('pm:policy', 'commit', 1, '[긴급] 프로모션 롤백 요청', NULL, NULL, NULL),
  ('pm:policy', 'commit', 2, '[정리] 스펙 코멘트 반영 완료', NULL, NULL, NULL),
  ('pm:policy', 'commit', 3, '[확정] 비회원 결제 오픈', NULL, NULL, NULL),
  ('pm:policy', 'commit', 4, '릴리즈 노트 공유드립니다', NULL, NULL, NULL),
  ('pm:policy', 'commit', 5, 'QA 시나리오 검토 완료', NULL, NULL, NULL),
  ('pm:policy', 'commit', 6, '[검토] 반품 정책 개정안', NULL, NULL, NULL),
  ('pm:policy', 'commit', 7, '[공유] 이번 주 지표 요약', NULL, NULL, NULL),
  ('pm:policy', 'commit', 8, '[확정] 등급 산정 기준', NULL, NULL, NULL),
  ('pm:policy', 'commit', 9, '유관부서 합의 완료', NULL, NULL, NULL),
  ('pm:policy', 'slack', 0, '이 정책 확정된 건가요?', '오늘 안에 확정합니다', NULL, NULL),
  ('pm:policy', 'slack', 1, 'CS 문의 답변 주셨나요?', '확인하고 회신했습니다', NULL, NULL),
  ('pm:policy', 'slack', 2, '요구사항 반영됐나요?', '문서에 업데이트했습니다', NULL, NULL),
  ('pm:policy', 'slack', 3, '일정 하루 당길 수 있나요?', '검토해보겠습니다', NULL, NULL),
  ('pm:policy', 'slack', 4, '이거 왜 이렇게 정했죠?', '배경 정리해서 드릴게요', NULL, NULL),
  ('pm:policy', 'slack', 5, '개발팀에 전달됐나요?', '티켓 만들어뒀습니다', NULL, NULL),
  ('pm:policy', 'slack', 6, '지표 어떻게 나왔나요?', '대시보드 공유드릴게요', NULL, NULL),
  ('pm:policy', 'slack', 7, '유관부서 합의됐나요?', '내일 미팅 잡혀 있습니다', NULL, NULL),
  ('pm:policy', 'slack', 8, '법무 검토 받으셨어요?', '어제 회신 받았습니다', NULL, NULL),
  ('pm:policy', 'slack', 9, '이번 스프린트 들어가나요?', '다음 차수로 밀렸습니다', NULL, NULL),
  ('pm:policy', 'slack', 10, '경쟁사는 어떻게 하죠?', '리서치 정리해뒀습니다', NULL, NULL),
  ('pm:policy', 'slack', 11, 'A/B 결과 나왔나요?', '유의미하지 않았습니다', NULL, NULL),
  ('design:design', 'bug', 0, 'contrast: 3.2:1', 'contrast: 4.5:1', 'QA — 저시력 사용자가 본문을 못 읽습니다. 본문 대비 하한은 4.5:1 입니다', '3.2 → 4.5'),
  ('design:design', 'bug', 1, 'tap-area: 36px', 'tap-area: 44px', 'QA — 아이폰 SE 에서 버튼이 안 눌립니다. 터치 영역 하한은 44px 입니다', '36 → 44'),
  ('design:design', 'bug', 2, 'background: #ffffff', 'background: color-bg-base', 'QA — 다크모드에서 배경이 흰색으로 남습니다. 하드코딩 대신 토큰을 쓰세요', '#ffffff → color-bg-base'),
  ('design:design', 'bug', 3, 'spacing-5: 18px', 'spacing-5: 20px', 'QA — 카드 간격이 그리드에서 어긋납니다. 스페이싱 스케일은 4의 배수입니다', '18 → 20'),
  ('design:design', 'bug', 4, 'text-body-md: 13px', 'text-body-md: 16px', 'QA — 본문이 캡션보다 작아 보입니다. 본문 기본은 16px 입니다', '13 → 16'),
  ('design:design', 'bug', 5, 'icon: ic_cart_20', 'icon: ic_cart_24', 'QA — 장바구니 아이콘만 작습니다. 이 화면은 24 세트입니다', '20 → 24'),
  ('design:design', 'bug', 6, 'focus-ring: none', 'focus-ring: 2px', 'QA — 키보드로 이동할 때 지금 어디인지 안 보입니다. 포커스 링은 2px 입니다', 'none → 2px'),
  ('design:design', 'bug', 7, 'disabled: opacity 0.9', 'disabled: opacity 0.4', 'QA — 비활성 버튼이 눌리는 줄 압니다. 비활성 투명도는 0.4 입니다', '0.9 → 0.4'),
  ('design:design', 'bug', 8, 'transition: 600ms', 'transition: 200ms', 'QA — 화면 전환이 답답합니다. 표준 전환은 200ms 입니다', '600 → 200'),
  ('design:design', 'bug', 9, 'shadow: rgba(0, 0, 0, .12', 'shadow: rgba(0, 0, 0, .12)', 'QA — 그림자가 아예 안 들어갑니다', ') 닫는 괄호'),
  ('design:design', 'bug', 10, 'radius-lg: 10px', 'radius-lg: 12px', 'QA — 카드 모서리가 버튼과 안 맞습니다. lg 는 12px 입니다', '10 → 12'),
  ('design:design', 'bug', 11, 'Modal z-index: 10', 'Modal z-index: 1000', 'QA — 모달이 헤더 뒤로 숨습니다. 모달 레이어는 1000 입니다', '10 → 1000'),
  ('design:design', 'bug', 12, 'line-height: 1.2', 'line-height: 1.5', 'QA — 본문 여러 줄이 답답합니다. 본문 행간은 1.5 입니다', '1.2 → 1.5'),
  ('design:design', 'bug', 13, 'letter-spacing: -0.5px', 'letter-spacing: -0.02em', 'QA — 큰 제목에서 자간이 과합니다. 자간은 상대 단위로 씁니다', 'px → em'),
  ('design:design', 'bug', 14, 'icon-btn tap: 24px', 'icon-btn tap: 40px', 'QA — 아이콘 버튼이 손가락으로 안 눌립니다. 아이콘 버튼 최소는 40px 입니다', '24 → 40'),
  ('design:design', 'bug', 15, 'skeleton: 3000ms', 'skeleton: 1000ms', 'QA — 로딩이 끝났는데 스켈레톤이 남아 있습니다', '3000 → 1000'),
  ('design:design', 'bug', 16, 'error-text: 10px', 'error-text: 12px', 'QA — 오류 문구가 너무 작아 안 읽힙니다. 보조 텍스트 하한은 12px 입니다', '10 → 12'),
  ('design:design', 'bug', 17, 'grid-gutter: 14px', 'grid-gutter: 16px', 'QA — 컬럼 간격이 8pt 그리드를 벗어났습니다', '14 → 16'),
  ('design:design', 'bug', 18, 'input-height: 40px', 'input-height: 48px', 'QA — 입력창이 옆 버튼보다 낮아 줄이 안 맞습니다. 폼 높이는 48px 입니다', '40 → 48'),
  ('design:design', 'bug', 19, 'toast: 1200ms', 'toast: 3000ms', 'QA — 토스트가 읽기도 전에 사라집니다. 기본 노출은 3000ms 입니다', '1200 → 3000'),
  ('design:design', 'commit', 0, 'Button/Primary/Hover', NULL, NULL, NULL),
  ('design:design', 'commit', 1, 'Card/Product/Sold-out', NULL, NULL, NULL),
  ('design:design', 'commit', 2, 'Modal/Confirm/Default', NULL, NULL, NULL),
  ('design:design', 'commit', 3, 'Input/Search/Focused', NULL, NULL, NULL),
  ('design:design', 'commit', 4, 'Chip/Filter/Selected', NULL, NULL, NULL),
  ('design:design', 'commit', 5, 'ic_cart_24.svg', NULL, NULL, NULL),
  ('design:design', 'commit', 6, 'Toast/Error/Default', NULL, NULL, NULL),
  ('design:design', 'commit', 7, 'Badge/Sale/Small', NULL, NULL, NULL),
  ('design:design', 'commit', 8, 'Tab/Bar/Active', NULL, NULL, NULL),
  ('design:design', 'commit', 9, 'Avatar/User/40', NULL, NULL, NULL),
  ('design:design', 'slack', 0, '시안 언제 볼 수 있나요?', '오늘 중으로 공유합니다', NULL, NULL),
  ('design:design', 'slack', 1, '이거 컴포넌트 있나요?', '라이브러리에 있습니다', NULL, NULL),
  ('design:design', 'slack', 2, '다크모드도 되나요?', '토큰으로 대응했습니다', NULL, NULL),
  ('design:design', 'slack', 3, '개발 전달 끝났나요?', 'Dev Mode 열어뒀습니다', NULL, NULL),
  ('design:design', 'slack', 4, '아이콘 하나만 더 될까요?', '내보내서 드릴게요', NULL, NULL),
  ('design:design', 'slack', 5, '이 여백 왜 이런가요?', '스페이싱 스케일입니다', NULL, NULL),
  ('design:design', 'slack', 6, '피그마 권한 좀 주세요', '방금 초대했습니다', NULL, NULL),
  ('design:design', 'slack', 7, '시안 두 개 중 뭐가 낫죠?', '첫 번째를 추천드립니다', NULL, NULL),
  ('design:design', 'slack', 8, '모바일도 그려주셨나요?', '브레이크포인트 나눴습니다', NULL, NULL),
  ('design:design', 'slack', 9, '접근성 검토 됐나요?', '대비까지 확인했습니다', NULL, NULL),
  ('design:design', 'slack', 10, '라이브러리 퍼블리시 했나요?', '방금 배포했습니다', NULL, NULL),
  ('design:design', 'slack', 11, '이 문구 확정인가요?', '기획팀에 확인하겠습니다', NULL, NULL);
